# Generated by Django 4.0.6 on 2022-07-30 05:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_checkoutview_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutview',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='e.g:0912 123 4567', max_length=12, region=None),
        ),
    ]
