# Generated by Django 4.0.6 on 2022-07-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_cartitem_quantity'),
        ('payments', '0004_checkoutview_cart_alter_checkoutview_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutview',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.cart'),
        ),
    ]
