# Generated by Django 4.0.6 on 2022-08-01 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_cartitem_order_alter_cartitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_alter_checkoutview_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutview',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='process.cart'),
        ),
        migrations.AlterField(
            model_name='checkoutview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
