# Generated by Django 4.0.6 on 2022-08-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_cartitem_order_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
