# Generated by Django 4.1 on 2022-08-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_cartitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_no',
            field=models.IntegerField(blank=True, default=1, unique=True, verbose_name='شماره سفارش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='وضعیت سفارش'),
            preserve_default=False,
        ),
    ]
