# Generated by Django 4.1 on 2022-08-23 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0008_alter_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_no',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('NP', 'Not-Paid'), ('P', 'Paid')], max_length=2, null=True, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='process.cart'),
            preserve_default=False,
        ),
    ]
