# Generated by Django 4.1 on 2022-08-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_remove_cart_order_no_alter_cart_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
    ]
