# Generated by Django 4.1 on 2022-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_remove_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='slug',
        ),
    ]
