# Generated by Django 4.0.6 on 2022-08-11 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='author_status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_special',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='special_user'),
        ),
    ]
