# Generated by Django 4.0.6 on 2022-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('wear', models.CharField(choices=[('T', 'T-shirt'), ('J', 'Jeens'), ('S', 'Shoes')], max_length=1)),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')], max_length=1)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
