# Generated by Django 4.1 on 2022-08-24 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('position', models.IntegerField(verbose_name='position')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='parents')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('vip', models.BooleanField(default=False, verbose_name='is_vip?')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='discount price')),
                ('active', models.BooleanField(default=True, verbose_name='is published ?')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='image2')),
                ('image', models.ImageField(default=None, upload_to='image/', verbose_name='image')),
                ('wear', models.CharField(choices=[('T', 'T-shirt'), ('J', 'Jeens'), ('S', 'Shoes')], max_length=1, verbose_name='product choice')),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')], max_length=1, verbose_name='size')),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'green'), ('R', 'Red'), ('BL', 'Blue')], max_length=2, verbose_name='color')),
                ('gender', models.CharField(choices=[('W', 'Womans'), ('M', 'Mans')], max_length=1, verbose_name='gender')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ManyToManyField(related_name='products', to='products.category', verbose_name='category')),
                ('hits', models.ManyToManyField(blank=True, related_name='hits', through='products.ArticleHit', to='products.ipaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='comment text')),
                ('stars', models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Good'), ('4', 'VeryGood'), ('5', 'Perfect')], max_length=50, verbose_name='your stars')),
                ('datetime_created', models.DateField(auto_now_add=True)),
                ('datetime_modified', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='articlehit',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ipaddress', verbose_name='ip_address'),
        ),
        migrations.AddField(
            model_name='articlehit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
    ]
