# Generated by Django 4.0.6 on 2022-07-23 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_color_product_gender_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_product',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Good'), ('4', 'VeryGood'), ('5', 'Perfect')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
