# Generated by Django 4.0.6 on 2022-07-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comment_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(verbose_name='body'),
        ),
    ]
