# Generated by Django 4.0.6 on 2022-07-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
