# Generated by Django 4.0.6 on 2022-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Good'), ('4', 'VeryGood'), ('5', 'Perfect')], max_length=50, verbose_name='your stars'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(verbose_name='comment text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'green'), ('R', 'Red'), ('BL', 'Blue')], max_length=2, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('W', 'Womans'), ('M', 'Mans')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='image/117515975.jpg', null=True, upload_to='image/', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')], max_length=1, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wear',
            field=models.CharField(choices=[('T', 'T-shirt'), ('J', 'Jeens'), ('S', 'Shoes')], max_length=1, verbose_name='product choice'),
        ),
    ]
