# Generated by Django 4.0.6 on 2022-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_comment_stars_alter_comment_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['position'],
            },
        ),
    ]
