# Generated by Django 4.1 on 2022-08-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='is_vip?'),
        ),
    ]
