# Generated by Django 4.1 on 2022-08-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_ipaddress_product_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hits',
        ),
    ]
